{% set name = "jupyterlab_templates" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9fc514791a648835aaa9cce3a7bdef387280929cd0959859980ad074c6569b6

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=3.5
  run:
    - python >=3.7
    - jupyterlab >=3.5

test:
  imports:
    - jupyterlab_templates

outputs:
  - name: jupyterlab_templates
  - name: jupyterlab-templates
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("jupyterlab_templates", exact=True) }}

about:
  home: https://github.com/finos/jupyterlab_templates
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Jupyter notebook templates
  description: Jupyter notebook templates
  dev_url: https://github.com/finos/jupyterlab_templates

extra:
  recipe-maintainers:
    - timkpaine
