{% set name = "jupyterlab_templates" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ee348ea0318033fcbd9274658c418d6cadafe89e9b3197e89c97f1cfde3eaff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - yarn
    - jupyter-packaging
  run:
    - python >=3.7
    - jupyterlab >=1.0.0

test:
  imports:
    - jupyterlab_templates

about:
  home: https://github.com/jpmorganchase/jupyterlab_templates
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Notebook templates

  description: |
    Notebook templates
  dev_url: https://github.com/jpmorganchase/jupyterlab_templates

extra:
  recipe-maintainers:
    - timkpaine
